SEED_DREAMS = [
    {
        "title": "끝없이 내려가는 계단",
        "dream_date": "2026-04-20",
        "content": "낯선 집 복도 끝에 있는 문을 열자 차가운 돌계단이 끝없이 이어졌다. 아래층으로 내려갈수록 발소리는 두 배로 울렸고, 뒤에서는 누가 따라오는 것 같은 기척이 점점 가까워졌다. 계단 벽에는 오래된 학교 시간표 같은 종이가 붙어 있었는데 읽으려 하면 글자가 젖은 것처럼 번졌다.",
        "tags": ["불안", "추격", "계단", "문", "낯선집"],
        "image_url": "/media/uploads/seed/seed-stairs.svg",
    },
    {
        "title": "시험장에 늦는 오전",
        "dream_date": "2026-04-18",
        "content": "학교 운동장을 가로질러 시험장으로 뛰어가는데 시계 초침만 빠르게 돌고 몸은 제자리걸음처럼 무거웠다. 교실 문을 열었을 때 모두가 이미 답안지를 뒤집고 있었고, 나는 이름도 기억나지 않는 과목 문제지를 받아 들고 멍하게 서 있었다.",
        "tags": ["당황", "시험", "지각", "학교"],
    },
    {
        "title": "밤바다 위를 낮게 나는 꿈",
        "dream_date": "2026-04-16",
        "content": "짙은 남색 밤바다 위를 아주 낮게 날았다. 파도 표면 가까이 내려갈 때마다 물결이 손끝에 스치고, 멀리서는 작은 불빛들이 등대인지 도시인지 구분되지 않았다. 두려움보다는 묘하게 평온해서 계속 날고 싶었다.",
        "tags": ["평온", "비행", "바다", "밤", "물"],
        "image_url": "/media/uploads/seed/seed-sea.svg",
    },
    {
        "title": "어린 시절 친구와 운동장",
        "dream_date": "2026-04-14",
        "content": "초등학교 운동장 한가운데에서 오래 연락하지 못한 어린 시절 친구를 만났다. 우리는 아무렇지 않게 이어달리기 순서를 정하고 웃었는데, 친구 얼굴은 분명 익숙한데 이름만 계속 떠오르지 않았다. 해가 질 무렵 친구가 먼저 집으로 간다고 손을 흔들었다.",
        "tags": ["그리움", "발견", "학교", "친구", "어린시절인물"],
    },
    {
        "title": "문 뒤에서 번지는 그림자",
        "dream_date": "2026-04-12",
        "content": "집 안 모든 불이 꺼진 상태에서 유일하게 복도 끝 문틈으로만 희미한 빛이 새어 나왔다. 가까이 다가가자 내 그림자가 아니라 훨씬 긴 그림자가 문 아래로 먼저 흘러나왔다. 문고리를 잡았을 때 안쪽에서 아주 낮은 숨소리가 들렸다.",
        "tags": ["공포", "혼란", "문", "그림자", "밤"],
    },
    {
        "title": "같은 골목을 몇 번이나",
        "dream_date": "2026-04-10",
        "content": "비슷한 간판이 늘어선 골목을 계속 걸었는데 분명 앞으로 가고 있는데도 같은 빵집과 같은 고양이가 반복해서 나타났다. 세 번째쯤 지나자 고양이가 나를 보고 먼저 길을 안내하듯 달렸고, 따라가자 처음 보는 작은 문이 열려 있었다.",
        "tags": ["혼란", "반복", "발견", "문", "동물"],
    },
    {
        "title": "가족과 바닷물 속 거실",
        "dream_date": "2026-04-08",
        "content": "거실 바닥까지 맑은 바닷물이 차오른 집에서 가족과 저녁을 먹고 있었다. 물속에서도 촛불은 꺼지지 않았고, 식탁 아래로 작은 물고기들이 지나갔다. 어머니는 평소처럼 반찬을 건네며 조금만 더 있으면 물이 빠질 거라고 말했다.",
        "tags": ["안도", "평온", "물", "바다", "가족"],
        "image_url": "/media/uploads/seed/seed-water-room.svg",
    },
    {
        "title": "누군가에게서 도망치는 옥상",
        "dream_date": "2026-04-06",
        "content": "학교 옥상 난간을 따라 달리는데 뒤에서 보이지 않는 사람이 일정한 속도로 따라왔다. 계단으로 내려가면 잡힐 것 같아서 결국 난간 위에 올라섰고, 발끝이 허공에 닿는 순간 아래가 바다가 아니라 검은 밤으로만 보였다.",
        "tags": ["불안", "도망", "추격", "학교", "밤"],
    },
    {
        "title": "불꽃이 피어나는 책장",
        "dream_date": "2026-04-04",
        "content": "도서관 책장 사이를 걷다가 한 권을 꺼내자 종이 사이에서 작은 불꽃이 피어올랐다. 불은 무섭기보다 촛불처럼 잔잔했고, 책 속 문장들이 반짝이며 공중으로 떠올랐다. 나는 타지 않도록 조심스럽게 손을 가까이 가져다 댔다.",
        "tags": ["기쁨", "발견", "불", "학교"],
    },
    {
        "title": "기차 창밖의 바다 학교",
        "dream_date": "2026-04-02",
        "content": "기차를 타고 학교에 가는데 창밖 풍경이 어느 순간 전부 바다로 바뀌었다. 교실은 객실처럼 흔들렸고, 선생님 대신 낯선 사람이 출석을 부르며 오늘은 파도 높이로 시험을 본다고 말했다. 친구들은 그 말을 당연하게 받아들였다.",
        "tags": ["혼란", "시험", "바다", "학교", "낯선사람"],
    },
    {
        "title": "변신하는 검은 고양이",
        "dream_date": "2026-03-31",
        "content": "검은 고양이를 따라 골목 끝까지 갔더니 갑자기 고양이가 사람처럼 서서 나를 바라봤다. 그 눈빛이 이상하게 친근해서 도망치지 못했고, 곧 고양이는 아주 어릴 적 사진 속 사촌의 얼굴로 변했다. 이름을 부르려는 순간 다시 그림자처럼 흩어졌다.",
        "tags": ["그리움", "변신", "동물", "그림자", "가족"],
        "image_url": "/media/uploads/seed/seed-cat.svg",
    },
    {
        "title": "하늘에서 떨어지기 직전",
        "dream_date": "2026-03-29",
        "content": "구름 위를 걷다가 발밑이 갑자기 갈라지며 아래로 떨어졌다. 몸은 무겁지 않았지만 끝없이 떨어지는 동안 지나온 장면들이 카드처럼 펼쳐졌고, 마지막에는 오래전에 헤어진 연인이 서 있는 문 앞에 멈췄다. 손을 뻗으려는 순간 잠에서 깼다.",
        "tags": ["공포", "추락", "상실", "연인", "문"],
    },
]

SEED_BOOK_DRAFTS = [
    {
        "title": "밤의 복도와 바다",
        "subtitle": "불안과 평온이 교차한 기록",
        "cover_phrase": "기억에서 사라지기 전에 붙잡아 둔 장면들",
        "cover_theme": "midnight-blue",
        "status": "finalized",
        "entry_titles": ["끝없이 내려가는 계단", "밤바다 위를 낮게 나는 꿈", "문 뒤에서 번지는 그림자"],
    },
    {
        "title": "다시 만난 얼굴들",
        "subtitle": "학교와 어린 시절 사이",
        "cover_phrase": "반복되는 장소에서 되살아나는 사람들",
        "cover_theme": "cream-dusk",
        "status": "finalized",
        "entry_titles": ["시험장에 늦는 오전", "어린 시절 친구와 운동장", "기차 창밖의 바다 학교", "변신하는 검은 고양이"],
    },
    {
        "title": "물빛과 그림자의 저녁",
        "subtitle": "잔잔한 물결 아래 남겨둔 기억",
        "cover_phrase": "조용한 장면들이 겹쳐진 밤의 기록",
        "cover_theme": "emerald-night",
        "status": "finalized",
        "entry_titles": ["가족과 바닷물 속 거실", "불꽃이 피어나는 책장", "하늘에서 떨어지기 직전"],
    },
    {
        "title": "끝없는 골목의 문",
        "subtitle": "반복되는 길 끝에서 만난 문장들",
        "cover_phrase": "익숙한 길 끝에서 조금 다른 장면을 만나다",
        "cover_theme": "starlit-plum",
        "status": "finalized",
        "entry_titles": ["같은 골목을 몇 번이나", "누군가에게서 도망치는 옥상", "끝없이 내려가는 계단"],
    },
    {
        "title": "미완성 장면들",
        "subtitle": "아직 한 권으로 묶지 않은 기록",
        "cover_phrase": "조금 더 다듬고 싶은 장면들",
        "cover_theme": "cream-dusk",
        "status": "draft",
        "entry_titles": ["밤바다 위를 낮게 나는 꿈", "어린 시절 친구와 운동장", "불꽃이 피어나는 책장"],
    },
    {
        "title": "파도 아래 남은 불빛",
        "subtitle": "늦은 밤 물결 위에 남겨진 숨결",
        "cover_phrase": "어둠 아래 오래 머문 파도의 기록",
        "cover_theme": "emerald-night",
        "status": "finalized",
        "entry_titles": ["밤바다 위를 낮게 나는 꿈", "가족과 바닷물 속 거실", "하늘에서 떨어지기 직전"],
    },
    {
        "title": "운동장 끝의 느린 오후",
        "subtitle": "익숙한 얼굴과 어긋난 시간",
        "cover_phrase": "오래전 오후가 천천히 다시 돌아오다",
        "cover_theme": "cream-dusk",
        "status": "finalized",
        "entry_titles": ["시험장에 늦는 오전", "어린 시절 친구와 운동장", "기차 창밖의 바다 학교"],
    },
    {
        "title": "그림자 너머의 서재",
        "subtitle": "불꽃과 종이 냄새가 머문 밤",
        "cover_phrase": "빛과 그림자 사이에서 꺼내 본 문장들",
        "cover_theme": "starlit-plum",
        "status": "finalized",
        "entry_titles": ["문 뒤에서 번지는 그림자", "불꽃이 피어나는 책장", "끝없이 내려가는 계단"],
    },
    {
        "title": "되돌아오는 골목의 밤",
        "subtitle": "몇 번이고 제자리로 돌아오는 풍경",
        "cover_phrase": "낯익은 골목에서 조금씩 달라지는 장면",
        "cover_theme": "midnight-blue",
        "status": "finalized",
        "entry_titles": ["같은 골목을 몇 번이나", "누군가에게서 도망치는 옥상", "변신하는 검은 고양이"],
    },
    {
        "title": "유리창 밖의 파란 수업",
        "subtitle": "창밖의 바다와 교실의 흔들림",
        "cover_phrase": "교실 밖으로 번져나간 파란 장면들",
        "cover_theme": "emerald-night",
        "status": "finalized",
        "entry_titles": ["기차 창밖의 바다 학교", "시험장에 늦는 오전", "밤바다 위를 낮게 나는 꿈"],
    },
    {
        "title": "고양이가 지나간 자리",
        "subtitle": "사라진 이름과 남겨진 발자국",
        "cover_phrase": "기억의 가장자리에서 다시 마주친 존재들",
        "cover_theme": "starlit-plum",
        "status": "finalized",
        "entry_titles": ["변신하는 검은 고양이", "어린 시절 친구와 운동장", "같은 골목을 몇 번이나"],
    },
]

SEED_ORDERS = [
    {
        "book_title": "밤의 복도와 바다",
        "quantity": 1,
        "status": "pending",
        "created_at": "2026-04-29T08:15:00",
        "updated_at": "2026-04-29T08:15:00",
    },
    {
        "book_title": "다시 만난 얼굴들",
        "quantity": 2,
        "status": "confirmed",
        "recipient_name": "김서윤",
        "recipient_phone": "010-8342-1176",
        "shipping_address": "서울특별시 마포구 독막로 118",
        "shipping_address_detail": "402호",
        "created_at": "2026-04-28T09:12:00",
        "updated_at": "2026-04-28T09:20:00",
        "history": [
            {"from_status": "pending", "to_status": "confirmed", "note": "seed-user-confirm", "changed_at": "2026-04-28T09:20:00"},
        ],
    },
    {
        "book_title": "물빛과 그림자의 저녁",
        "quantity": 1,
        "status": "confirmed",
        "recipient_name": "정하율",
        "recipient_phone": "010-2927-6401",
        "shipping_address": "경기도 수원시 영통구 광교중앙로 145",
        "shipping_address_detail": "1502호",
        "created_at": "2026-04-28T14:05:00",
        "updated_at": "2026-04-28T14:11:00",
        "history": [
            {"from_status": "pending", "to_status": "confirmed", "note": "seed-user-confirm", "changed_at": "2026-04-28T14:11:00"},
        ],
    },
    {
        "book_title": "끝없는 골목의 문",
        "quantity": 3,
        "status": "confirmed",
        "recipient_name": "윤지후",
        "recipient_phone": "010-6213-0984",
        "shipping_address": "대전광역시 서구 둔산로 77",
        "shipping_address_detail": "901호",
        "admin_memo": "선물 포장 요청 확인 필요",
        "created_at": "2026-04-27T18:42:00",
        "updated_at": "2026-04-27T18:58:00",
        "history": [
            {"from_status": "pending", "to_status": "confirmed", "note": "seed-user-confirm", "changed_at": "2026-04-27T18:58:00"},
        ],
    },
    {
        "book_title": "미완성 장면들",
        "quantity": 2,
        "status": "processing",
        "recipient_name": "박소민",
        "recipient_phone": "010-4577-3025",
        "shipping_address": "부산광역시 수영구 광안해변로 219",
        "shipping_address_detail": "101동 2003호",
        "admin_memo": "인쇄 파일 최종 확인 완료",
        "created_at": "2026-04-26T11:03:00",
        "updated_at": "2026-04-27T09:30:00",
        "history": [
            {"from_status": "pending", "to_status": "confirmed", "note": "seed-user-confirm", "changed_at": "2026-04-26T11:14:00"},
            {"from_status": "confirmed", "to_status": "processing", "note": "seed-admin-production", "changed_at": "2026-04-27T09:30:00"},
        ],
    },
    {
        "book_title": "파도 아래 남은 불빛",
        "quantity": 1,
        "status": "processing",
        "recipient_name": "최도윤",
        "recipient_phone": "010-7814-6652",
        "shipping_address": "인천광역시 연수구 센트럴로 123",
        "shipping_address_detail": "602동 1904호",
        "admin_memo": "제본 대기 중",
        "created_at": "2026-04-25T16:20:00",
        "updated_at": "2026-04-26T13:10:00",
        "history": [
            {"from_status": "pending", "to_status": "confirmed", "note": "seed-user-confirm", "changed_at": "2026-04-25T16:32:00"},
            {"from_status": "confirmed", "to_status": "processing", "note": "seed-admin-production", "changed_at": "2026-04-26T13:10:00"},
        ],
    },
    {
        "book_title": "운동장 끝의 느린 오후",
        "quantity": 3,
        "status": "shipped",
        "recipient_name": "한예린",
        "recipient_phone": "010-5148-1139",
        "shipping_address": "대구광역시 중구 동성로2길 80",
        "shipping_address_detail": "3층",
        "created_at": "2026-04-24T10:15:00",
        "updated_at": "2026-04-27T17:45:00",
        "history": [
            {"from_status": "pending", "to_status": "confirmed", "note": "seed-user-confirm", "changed_at": "2026-04-24T10:24:00"},
            {"from_status": "confirmed", "to_status": "processing", "note": "seed-admin-production", "changed_at": "2026-04-25T09:05:00"},
            {"from_status": "processing", "to_status": "shipped", "note": "seed-admin-shipped", "changed_at": "2026-04-27T17:45:00"},
        ],
    },
    {
        "book_title": "그림자 너머의 서재",
        "quantity": 2,
        "status": "shipped",
        "recipient_name": "이준서",
        "recipient_phone": "010-3702-8841",
        "shipping_address": "경기도 성남시 분당구 판교역로 166",
        "shipping_address_detail": "B동 1211호",
        "created_at": "2026-04-23T15:30:00",
        "updated_at": "2026-04-28T08:55:00",
        "history": [
            {"from_status": "pending", "to_status": "confirmed", "note": "seed-user-confirm", "changed_at": "2026-04-23T15:44:00"},
            {"from_status": "confirmed", "to_status": "processing", "note": "seed-admin-production", "changed_at": "2026-04-24T11:00:00"},
            {"from_status": "processing", "to_status": "shipped", "note": "seed-admin-shipped", "changed_at": "2026-04-28T08:55:00"},
        ],
    },
    {
        "book_title": "되돌아오는 골목의 밤",
        "quantity": 1,
        "status": "received",
        "recipient_name": "오채린",
        "recipient_phone": "010-6881-2207",
        "shipping_address": "광주광역시 북구 첨단연신로 108",
        "shipping_address_detail": "702호",
        "created_at": "2026-04-21T09:40:00",
        "updated_at": "2026-04-28T20:14:00",
        "history": [
            {"from_status": "pending", "to_status": "confirmed", "note": "seed-user-confirm", "changed_at": "2026-04-21T09:52:00"},
            {"from_status": "confirmed", "to_status": "processing", "note": "seed-admin-production", "changed_at": "2026-04-22T14:10:00"},
            {"from_status": "processing", "to_status": "shipped", "note": "seed-admin-shipped", "changed_at": "2026-04-25T17:35:00"},
            {"from_status": "shipped", "to_status": "received", "note": "seed-user-received", "changed_at": "2026-04-28T20:14:00"},
        ],
    },
    {
        "book_title": "유리창 밖의 파란 수업",
        "quantity": 1,
        "status": "cancelled",
        "recipient_name": "문하람",
        "recipient_phone": "010-2294-5108",
        "shipping_address": "제주특별자치도 제주시 연북로 55",
        "shipping_address_detail": "104호",
        "created_at": "2026-04-22T13:18:00",
        "updated_at": "2026-04-22T15:02:00",
        "history": [
            {"from_status": "pending", "to_status": "confirmed", "note": "seed-user-confirm", "changed_at": "2026-04-22T13:29:00"},
            {"from_status": "confirmed", "to_status": "cancelled", "note": "seed-user-cancel", "changed_at": "2026-04-22T15:02:00"},
        ],
    },
    {
        "book_title": "고양이가 지나간 자리",
        "quantity": 2,
        "status": "confirmed",
        "recipient_name": "강민아",
        "recipient_phone": "010-9441-3082",
        "shipping_address": "울산광역시 남구 삼산로 247",
        "shipping_address_detail": "9층 904호",
        "created_at": "2026-04-29T10:05:00",
        "updated_at": "2026-04-29T10:16:00",
        "history": [
            {"from_status": "pending", "to_status": "confirmed", "note": "seed-user-confirm", "changed_at": "2026-04-29T10:16:00"},
        ],
    },
]
