SEED_DREAMS = [
    {
        "title": "끝없이 내려가는 계단",
        "dream_date": "2026-04-20",
        "content": "낯선 집 복도 끝에 있는 문을 열자 차가운 돌계단이 끝없이 이어졌다. 아래층으로 내려갈수록 발소리는 두 배로 울렸고, 뒤에서는 누가 따라오는 것 같은 기척이 점점 가까워졌다. 계단 벽에는 오래된 학교 시간표 같은 종이가 붙어 있었는데 읽으려 하면 글자가 젖은 것처럼 번졌다.",
        "tags": ["불안", "추격", "계단", "문", "낯선집"],
        "uploaded_image_url": "/media/uploads/seed/seed-stairs.svg",
    },
    {
        "title": "시험장에 늦는 오전",
        "dream_date": "2026-04-18",
        "content": "학교 운동장을 가로질러 시험장으로 뛰어가는데 시계 초침만 빠르게 돌고 몸은 제자리걸음처럼 무거웠다. 교실 문을 열었을 때 모두가 이미 답안지를 뒤집고 있었고, 나는 이름도 기억나지 않는 과목 문제지를 받아 들고 멍하게 서 있었다.",
        "tags": ["당황", "시험", "지각", "학교"],
    },
    {
        "title": "밤바다 위를 낮게 나는 꿈",
        "dream_date": "2026-04-16",
        "content": "짙은 남색 밤바다 위를 아주 낮게 날았다. 파도 표면 가까이 내려갈 때마다 물결이 손끝에 스치고, 멀리서는 작은 불빛들이 등대인지 도시인지 구분되지 않았다. 두려움보다는 묘하게 평온해서 계속 날고 싶었다.",
        "tags": ["평온", "비행", "바다", "밤", "물"],
        "uploaded_image_url": "/media/uploads/seed/seed-sea.svg",
    },
    {
        "title": "어린 시절 친구와 운동장",
        "dream_date": "2026-04-14",
        "content": "초등학교 운동장 한가운데에서 오래 연락하지 못한 어린 시절 친구를 만났다. 우리는 아무렇지 않게 이어달리기 순서를 정하고 웃었는데, 친구 얼굴은 분명 익숙한데 이름만 계속 떠오르지 않았다. 해가 질 무렵 친구가 먼저 집으로 간다고 손을 흔들었다.",
        "tags": ["그리움", "발견", "학교", "친구", "어린시절인물"],
    },
    {
        "title": "문 뒤에서 번지는 그림자",
        "dream_date": "2026-04-12",
        "content": "집 안 모든 불이 꺼진 상태에서 유일하게 복도 끝 문틈으로만 희미한 빛이 새어 나왔다. 가까이 다가가자 내 그림자가 아니라 훨씬 긴 그림자가 문 아래로 먼저 흘러나왔다. 문고리를 잡았을 때 안쪽에서 아주 낮은 숨소리가 들렸다.",
        "tags": ["공포", "혼란", "문", "그림자", "밤"],
    },
    {
        "title": "같은 골목을 몇 번이나",
        "dream_date": "2026-04-10",
        "content": "비슷한 간판이 늘어선 골목을 계속 걸었는데 분명 앞으로 가고 있는데도 같은 빵집과 같은 고양이가 반복해서 나타났다. 세 번째쯤 지나자 고양이가 나를 보고 먼저 길을 안내하듯 달렸고, 따라가자 처음 보는 작은 문이 열려 있었다.",
        "tags": ["혼란", "반복", "발견", "문", "동물"],
    },
    {
        "title": "가족과 바닷물 속 거실",
        "dream_date": "2026-04-08",
        "content": "거실 바닥까지 맑은 바닷물이 차오른 집에서 가족과 저녁을 먹고 있었다. 물속에서도 촛불은 꺼지지 않았고, 식탁 아래로 작은 물고기들이 지나갔다. 어머니는 평소처럼 반찬을 건네며 조금만 더 있으면 물이 빠질 거라고 말했다.",
        "tags": ["안도", "평온", "물", "바다", "가족"],
        "uploaded_image_url": "/media/uploads/seed/seed-water-room.svg",
    },
    {
        "title": "누군가에게서 도망치는 옥상",
        "dream_date": "2026-04-06",
        "content": "학교 옥상 난간을 따라 달리는데 뒤에서 보이지 않는 사람이 일정한 속도로 따라왔다. 계단으로 내려가면 잡힐 것 같아서 결국 난간 위에 올라섰고, 발끝이 허공에 닿는 순간 아래가 바다가 아니라 검은 밤으로만 보였다.",
        "tags": ["불안", "도망", "추격", "학교", "밤"],
    },
    {
        "title": "불꽃이 피어나는 책장",
        "dream_date": "2026-04-04",
        "content": "도서관 책장 사이를 걷다가 한 권을 꺼내자 종이 사이에서 작은 불꽃이 피어올랐다. 불은 무섭기보다 촛불처럼 잔잔했고, 책 속 문장들이 반짝이며 공중으로 떠올랐다. 나는 타지 않도록 조심스럽게 손을 가까이 가져다 댔다.",
        "tags": ["기쁨", "발견", "불", "학교"],
    },
    {
        "title": "기차 창밖의 바다 학교",
        "dream_date": "2026-04-02",
        "content": "기차를 타고 학교에 가는데 창밖 풍경이 어느 순간 전부 바다로 바뀌었다. 교실은 객실처럼 흔들렸고, 선생님 대신 낯선 사람이 출석을 부르며 오늘은 파도 높이로 시험을 본다고 말했다. 친구들은 그 말을 당연하게 받아들였다.",
        "tags": ["혼란", "시험", "바다", "학교", "낯선사람"],
    },
    {
        "title": "변신하는 검은 고양이",
        "dream_date": "2026-03-31",
        "content": "검은 고양이를 따라 골목 끝까지 갔더니 갑자기 고양이가 사람처럼 서서 나를 바라봤다. 그 눈빛이 이상하게 친근해서 도망치지 못했고, 곧 고양이는 아주 어릴 적 사진 속 사촌의 얼굴로 변했다. 이름을 부르려는 순간 다시 그림자처럼 흩어졌다.",
        "tags": ["그리움", "변신", "동물", "그림자", "가족"],
        "uploaded_image_url": "/media/uploads/seed/seed-cat.svg",
    },
    {
        "title": "하늘에서 떨어지기 직전",
        "dream_date": "2026-03-29",
        "content": "구름 위를 걷다가 발밑이 갑자기 갈라지며 아래로 떨어졌다. 몸은 무겁지 않았지만 끝없이 떨어지는 동안 지나온 장면들이 카드처럼 펼쳐졌고, 마지막에는 오래전에 헤어진 연인이 서 있는 문 앞에 멈췄다. 손을 뻗으려는 순간 잠에서 깼다.",
        "tags": ["공포", "추락", "상실", "연인", "문"],
    },
]

SEED_BOOK_DRAFTS = [
    {
        "title": "밤의 복도와 바다",
        "subtitle": "불안과 평온이 교차한 기록",
        "cover_phrase": "기억에서 사라지기 전에 붙잡아 둔 장면들",
        "cover_theme": "midnight-blue",
        "status": "finalized",
        "entry_titles": ["끝없이 내려가는 계단", "밤바다 위를 낮게 나는 꿈", "문 뒤에서 번지는 그림자"],
    },
    {
        "title": "다시 만난 얼굴들",
        "subtitle": "학교와 어린 시절 사이",
        "cover_phrase": "반복되는 장소에서 되살아나는 사람들",
        "cover_theme": "cream-dusk",
        "status": "finalized",
        "entry_titles": ["시험장에 늦는 오전", "어린 시절 친구와 운동장", "기차 창밖의 바다 학교", "변신하는 검은 고양이"],
    },
    {
        "title": "물빛과 그림자의 저녁",
        "subtitle": "잔잔한 물결 아래 남겨둔 기억",
        "cover_phrase": "조용한 장면들이 겹쳐진 밤의 기록",
        "cover_theme": "emerald-night",
        "status": "finalized",
        "entry_titles": ["가족과 바닷물 속 거실", "불꽃이 피어나는 책장", "하늘에서 떨어지기 직전"],
    },
    {
        "title": "끝없는 골목의 문",
        "subtitle": "반복되는 길 끝에서 만난 문장들",
        "cover_phrase": "익숙한 길 끝에서 조금 다른 장면을 만나다",
        "cover_theme": "starlit-plum",
        "status": "finalized",
        "entry_titles": ["같은 골목을 몇 번이나", "누군가에게서 도망치는 옥상", "끝없이 내려가는 계단"],
    },
    {
        "title": "미완성 장면들",
        "subtitle": "아직 한 권으로 묶지 않은 기록",
        "cover_phrase": "조금 더 다듬고 싶은 장면들",
        "cover_theme": "cream-dusk",
        "status": "draft",
        "entry_titles": ["밤바다 위를 낮게 나는 꿈", "어린 시절 친구와 운동장", "불꽃이 피어나는 책장"],
    },
]

SEED_ORDERS = [
    {"book_title": "밤의 복도와 바다", "quantity": 1, "status": "pending"},
    {
        "book_title": "다시 만난 얼굴들",
        "quantity": 2,
        "status": "confirmed",
        "recipient_name": "김서윤",
        "recipient_phone": "010-1234-5678",
        "shipping_address": "서울특별시 마포구 월드컵북로 12",
        "shipping_address_detail": "203호",
    },
    {
        "book_title": "물빛과 그림자의 저녁",
        "quantity": 1,
        "status": "processing",
        "recipient_name": "이하준",
        "recipient_phone": "010-2468-1357",
        "shipping_address": "부산광역시 수영구 광안해변로 24",
        "shipping_address_detail": "12층 1203호",
        "export_status": "pending",
        "admin_memo": "메타데이터 추출 대기 상태 확인용",
    },
    {
        "book_title": "끝없는 골목의 문",
        "quantity": 1,
        "status": "shipped",
        "recipient_name": "박지우",
        "recipient_phone": "010-9999-2468",
        "shipping_address": "대구광역시 수성구 달구벌대로 101",
        "shipping_address_detail": "상가동 402호",
        "export_status": "completed",
    },
    {
        "book_title": "밤의 복도와 바다",
        "quantity": 3,
        "status": "processing",
        "recipient_name": "최유리",
        "recipient_phone": "010-3141-5926",
        "shipping_address": "서울특별시 성동구 성수이로 77",
        "shipping_address_detail": "7층 701호",
        "export_status": "pending",
        "admin_memo": "관리자 페이지 추출 일괄 실행 테스트용",
    },
    {
        "book_title": "물빛과 그림자의 저녁",
        "quantity": 2,
        "status": "processing",
        "recipient_name": "오민재",
        "recipient_phone": "010-2718-2818",
        "shipping_address": "경기도 성남시 분당구 판교역로 166",
        "shipping_address_detail": "B동 1211호",
        "export_status": "failed",
        "export_error": "seed: 이미지 아카이브 생성 중 타임아웃이 발생했습니다.",
        "admin_memo": "추출 실패 재시도 버튼 테스트용",
    },
    {
        "book_title": "끝없는 골목의 문",
        "quantity": 1,
        "status": "processing",
        "recipient_name": "장하린",
        "recipient_phone": "010-5772-1994",
        "shipping_address": "광주광역시 북구 첨단과기로 88",
        "shipping_address_detail": "201동 1502호",
        "export_status": "completed",
        "admin_memo": "이미 추출 완료된 제작 중 주문 테스트용",
    },
]
